name: strawberry_diagnosis
description: An app to upload strawberry images and diagnose diseases using AWS Amplify.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^3.0.3

  # Amplify packages
  amplify_flutter: ^2.6.1
  amplify_auth_cognito: ^2.6.1
  amplify_storage_s3: ^2.6.1
  amplify_api: ^2.6.1

  # Firebase packages
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_analytics: ^11.5.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^6.2.1

  # Utilities
  image_picker: ^1.1.2
  file_picker: ^10.2.0
  flutter_svg: ^2.0.7
  flutter_dotenv: ^5.1.0
  uuid: ^4.3.3
  material: ^1.0.0+2
  camera: ^0.11.2
  shared_preferences: ^2.3.2  # ✅ Added for storing scan guide status

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/amplifyconfiguration.dart
    - images/google.png
    - assets/images/hero_card_picture.jpg
    - assets/images/recent_scan_placeholder.jpg
    - images/logo.jpg
    - assets/illustrations/undraw_no-data_ig65.svg

  fonts:
    - family: DM Sans
      fonts:
        - asset: fonts/DM_Sans/static/DMSans-Regular.ttf
        - asset: fonts/DM_Sans/static/DMSans-Bold.ttf
          weight: 700
